try:
  raise Exception('An error!')
except Exception as e:
  print(e)
